# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gabrielle Bastien
email: gabrielle.bastien1@gmail.com
description: Gabrielle Bastien - Développeuse web front-end
url: "https://gbastien1.github.io" # the base hostname & protocol for your site
github_username:  gbastien1
linkedin_url:     https://www.linkedin.com/in/gabrielle-bastien-829400104/


# Build settings
markdown: kramdown
highlighter: rouge

# site
lang:             fr

# Permalinks
permalink:        pretty

# Server
destination:      _gh_pages
host:             127.0.0.1
port:             9001
baseurl:          /
encoding:         UTF-8
livereload: true 

# collections
collections:
  projects:
    output: true

assets:
  sources:
    -_assets/fonts